in:
  type: file
  path_prefix: /workspaces/embulk_test/try2_bq/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}

filters:
- type: add_time
  to_column:
    name: uploaded_at
    type: timestamp
  from_value:
    mode: upload_time

out:
  type: bigquery
  mode: append
  location: asia-northeast1
  auth_method: authorized_user
  json_keyfile: /root/.config/gcloud/application_default_credentials.json
  project: 
  dataset: 
  table: 
  compression: NONE
  source_format: CSV
  gcs_bucket: 
  auto_create_gcs_bucket: true